//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dang_Nhap
    {
        public string id_DangNhap { get; set; }
        public string Ten_DN { get; set; }
        public string Mat_Khau { get; set; }
    }
}
