//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopLucShopEntities : DbContext
    {
        public HopLucShopEntities()
            : base("name=HopLucShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dang_Nhap> Dang_Nhap { get; set; }
        public DbSet<HoaDon> HoaDon { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<LoaiSP> LoaiSP { get; set; }
        public DbSet<NhanVienBH> NhanVienBH { get; set; }
        public DbSet<PhieuNhap> PhieuNhap { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
    }
}
