//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public byte ID_KH { get; set; }
        public string Ten_KH { get; set; }
        public string Dia_Chi { get; set; }
        public Nullable<decimal> SDT_KH { get; set; }
        public string Email_KH { get; set; }
    
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
