//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        public LoaiSP()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public byte ID_Loai { get; set; }
        public string Ten_Loai_SP { get; set; }
    
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
