//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienBH
    {
        public NhanVienBH()
        {
            this.HoaDon = new HashSet<HoaDon>();
            this.PhieuNhap = new HashSet<PhieuNhap>();
        }
    
        public byte ID_NV { get; set; }
        public string Ten_NV { get; set; }
        public string Dia_Chi_NV { get; set; }
        public Nullable<decimal> SDT_NV { get; set; }
        public string Email_NV { get; set; }
    
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhap { get; set; }
    }
}
