//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public byte ID_PN { get; set; }
        public Nullable<System.DateTime> Ngay_Gio { get; set; }
        public string Ghi_Chu { get; set; }
        public Nullable<byte> ID_NV { get; set; }
        public Nullable<byte> ID_SP { get; set; }
    
        public virtual NhanVienBH NhanVienBH { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
