//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopLucAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.HoaDon = new HashSet<HoaDon>();
            this.PhieuNhap = new HashSet<PhieuNhap>();
        }
    
        public byte ID_SP { get; set; }
        public string Ma_SP { get; set; }
        public string Ten_SP { get; set; }
        public string Mo_Ta { get; set; }
        public short SL { get; set; }
        public decimal Gia_Ban { get; set; }
        public decimal Gia_Nhap { get; set; }
        public Nullable<byte> ID_Loai_SP { get; set; }
        public Nullable<short> Ton_Kho { get; set; }
    
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual ICollection<PhieuNhap> PhieuNhap { get; set; }
    }
}
